import Head from "next/head";
import SidebarSecondary from "@/components/SidebarSecondary/SidebarSecondary";
import RatingDetailed from "@/components/RatingDetailed/RatingDetailed";
import ProductOverview from "@/components/ProductOverview/ProductOverview";
import Container from "@/components/Container/Container";
import ContainerMainFixedAside from "@/components/ContainerMainFixedAside/ContainerMainFixedAside";
import ContainerMainContent from "@/components/ContainerMainContent/ContainerMainContent";
import useCartItemsStore from "@/store/useCartItemsStore";
import Box from "@/components/Box/Box";

import * as S from "./ProductDetails.styled";

import { Element } from "react-scroll";

import iconOverview from "@/assets/images/overview.svg";
import iconSupplier from "@/assets/images/seller.svg";
import iconProducts from "@/assets/images/products.svg";
import iconReviews from "@/assets/images/reviews.svg";

import { supplier, product } from "@/dummy-data/suppliers";

const menuList = [
  {
    title: "Overview",
    icon: iconOverview,
    url: "/suppliers/supplier1/product1#overview",
    key: "1",
  },
  {
    title: "Supplier Details",
    icon: iconSupplier,
    url: "/suppliers/supplier1/product1#contact",
    key: "2",
  },
  {
    title: "Product Details",
    icon: iconProducts,
    url: "/suppliers/supplier1/product1#products",
    key: "3",
  },
  {
    title: "Reviews",
    icon: iconReviews,
    url: "/suppliers/supplier1/product1#reviews",
    key: "4",
  },
];

export const ProductDetails: any = () => {
  const addCartItem = useCartItemsStore((state) => state.addCartItem);
  const updateQuantity = useCartItemsStore((state) => state.updateQuantity);

  return (
    <>
      <Head>
        <title>{product.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <SidebarSecondary menuList={menuList} selected="1" onLinkClick />
        <ContainerMainFixedAside>
          <ContainerMainContent>
            <Element name="Overview">
              <Box title="Overview" id={"overview"}>
                <ProductOverview
                  data={product}
                  addToCart={(product: any) => {
                    addCartItem(product);
                  }}
                  updateQuantity={(productID: string, quantity: number) => {
                    updateQuantity(productID, quantity! + 1);
                  }}
                />
              </Box>
            </Element>
            <Element name="Supplier Details">
              <Box title="Supplier Details" id={"supplierDetails"}>
                <S.SupplierOverView data={supplier} />
              </Box>
            </Element>
            <Element name="Product Details">
              <Box title="Product Details" id={"productDetails"}>
                <S.InfoBlock>
                  <S.SubTitle1>Product Description</S.SubTitle1>
                  <S.TextSmall>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                    do eiusmod tempor incididunt ut labore et dolore magna
                    aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                    ullamco laboris nisi ut aliquip ex ea commodo consequat.
                    Duis aute irure dolor in reprehenderit in voluptate velit
                    esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
                    occaecat cupidatat non proident, sunt in culpa qui officia
                    deserunt mollit anim id est laborum.
                  </S.TextSmall>
                  <S.TextSmall>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                    do eiusmod tempor incididunt ut labore et dolore magna
                    aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                    ullamco laboris nisi ut aliquip ex ea commodo consequat.
                  </S.TextSmall>
                </S.InfoBlock>
                <S.InfoBlock>
                  <S.SubTitle1>Product Information</S.SubTitle1>
                  <S.TextGrid>
                    <div>
                      <S.SubTitle2>Technical Details</S.SubTitle2>
                      <S.TextSmall>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit,
                        sed do eiusmod tempor incididunt ut labore et dolore
                        magna aliqua. Ut enim ad minim veniam, quis nostrud
                        exercitation ullamco laboris nisi ut aliquip ex ea
                        commodo consequat.
                      </S.TextSmall>
                    </div>
                    <div>
                      <S.SubTitle2>Additional Details</S.SubTitle2>
                      <S.TextSmall>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit,
                        sed do eiusmod tempor incididunt ut labore et dolore
                        magna aliqua. Ut enim ad minim veniam, quis nostrud
                        exercitation ullamco laboris nisi ut aliquip ex ea
                        commodo consequat.
                      </S.TextSmall>
                    </div>
                  </S.TextGrid>
                </S.InfoBlock>
                <S.InfoBlock>
                  <S.SubTitle1>In the Box:</S.SubTitle1>
                  <S.TextList>
                    <S.TextListLi>2 x Lorem Ipsum</S.TextListLi>
                    <S.TextListLi>2 x Lorem Ipsum</S.TextListLi>
                    <S.TextListLi>2 x Lorem Ipsum</S.TextListLi>
                    <S.TextListLi>2 x Lorem Ipsum</S.TextListLi>
                  </S.TextList>
                </S.InfoBlock>
              </Box>
            </Element>
            <Element name="Reviews">
              <Box title="Reviews" id={"reviews"}>
                <S.SummaryRatingOverview
                  size="large"
                  rating={supplier.review}
                />
                <RatingDetailed ratingDetail={supplier.ratingDetail} />
              </Box>
            </Element>
          </ContainerMainContent>
        </ContainerMainFixedAside>
      </Container>
    </>
  );
};
