import productImage from "@/assets/temp-images/product1.jpg";
import supplierLogo from "@/assets/temp-images/supplier.jpg";

export const products = [
  {
    name: "Black+Decker 154 Pieces Hand Tool Kit for Home & Office Use, Orange/Black",
    url: "/suppliers/supplier1/product1",
    price: 132.99,
    currency: "AED",
    image: { productImage },
    imageAlt: "Black and decker",
    review: {
      verdict: "Very Good",
      count: 5083,
    },
    supplier: "ACME",
    supplierLogo: { supplierLogo },
    supplierLocation: "RAK",
    supplierReview: {
      verdict: "Very Good",
      count: 583,
    },
    supplierLegacy: {
      value: 3,
      units: "YRS",
    },
  },
  {
    name: "Black+Decker 154 Pieces Hand Tool Kit for Home & Office Use, Orange/Black",
    url: "/suppliers/supplier1/product1",
    price: 132.99,
    currency: "AED",
    image: { productImage },
    imageAlt: "Black and decker",
    review: {
      verdict: "Very Good",
      count: 5083,
    },
    supplier: "ACME",
    supplierLogo: { supplierLogo },
    supplierLocation: "RAK",
    supplierReview: {
      verdict: "Very Good",
      count: 583,
    },
    supplierLegacy: {
      value: 3,
      units: "YRS",
    },
  },
  {
    name: "Black+Decker 154 Pieces Hand Tool Kit for Home & Office Use, Orange/Black",
    url: "/suppliers/supplier1/product1",
    price: 132.99,
    currency: "AED",
    image: { productImage },
    imageAlt: "Black and decker",
    review: {
      verdict: "Very Good",
      count: 5083,
    },
    supplier: "ACME",
    supplierLogo: { supplierLogo },
    supplierLocation: "RAK",
    supplierReview: {
      verdict: "Very Good",
      count: 583,
    },
    supplierLegacy: {
      value: 3,
      units: "YRS",
    },
  },
  {
    name: "Black+Decker 154 Pieces Hand Tool Kit for Home & Office Use, Orange/Black",
    url: "/suppliers/supplier1/product1",
    price: 132.99,
    currency: "AED",
    image: { productImage },
    imageAlt: "Black and decker",
    review: {
      verdict: "Very Good",
      count: 5083,
    },
    supplier: "ACME",
    supplierLogo: { supplierLogo },
    supplierLocation: "RAK",
    supplierReview: {
      verdict: "Very Good",
      count: 583,
    },
    supplierLegacy: {
      value: 3,
      units: "YRS",
    },
  },
  {
    name: "Black+Decker 154 Pieces Hand Tool Kit for Home & Office Use, Orange/Black",
    url: "/suppliers/supplier1/product1",
    price: 132.99,
    currency: "AED",
    image: { productImage },
    imageAlt: "Black and decker",
    review: {
      verdict: "Very Good",
      count: 5083,
    },
    supplier: "ACME",
    supplierLogo: { supplierLogo },
    supplierLocation: "RAK",
    supplierReview: {
      verdict: "Very Good",
      count: 583,
    },
    supplierLegacy: {
      value: 3,
      units: "YRS",
    },
  },
  {
    name: "Black+Decker 154 Pieces Hand Tool Kit for Home & Office Use, Orange/Black",
    url: "/suppliers/supplier1/product1",
    price: 132.99,
    currency: "AED",
    image: { productImage },
    imageAlt: "Black and decker",
    review: {
      verdict: "Very Good",
      count: 5083,
    },
    supplier: "ACME",
    supplierLogo: { supplierLogo },
    supplierLocation: "RAK",
    supplierReview: {
      verdict: "Very Good",
      count: 583,
    },
    supplierLegacy: {
      value: 3,
      units: "YRS",
    },
  },
  {
    name: "Black+Decker 154 Pieces Hand Tool Kit for Home & Office Use, Orange/Black",
    url: "/suppliers/supplier1/product1",
    price: 132.99,
    currency: "AED",
    image: { productImage },
    imageAlt: "Black and decker",
    review: {
      verdict: "Very Good",
      count: 5083,
    },
    supplier: "ACME",
    supplierLogo: { supplierLogo },
    supplierLocation: "RAK",
    supplierReview: {
      verdict: "Very Good",
      count: 583,
    },
    supplierLegacy: {
      value: 3,
      units: "YRS",
    },
  },
  {
    name: "Black+Decker 154 Pieces Hand Tool Kit for Home & Office Use, Orange/Black",
    url: "/suppliers/supplier1/product1",
    price: 132.99,
    currency: "AED",
    image: { productImage },
    imageAlt: "Black and decker",
    review: {
      verdict: "Very Good",
      count: 5083,
    },
    supplier: "ACME",
    supplierLogo: { supplierLogo },
    supplierLocation: "RAK",
    supplierReview: {
      verdict: "Very Good",
      count: 583,
    },
    supplierLegacy: {
      value: 3,
      units: "YRS",
    },
  },
  {
    name: "Black+Decker 154 Pieces Hand Tool Kit for Home & Office Use, Orange/Black",
    url: "/suppliers/supplier1/product1",
    price: 132.99,
    currency: "AED",
    image: { productImage },
    imageAlt: "Black and decker",
    review: {
      verdict: "Very Good",
      count: 5083,
    },
    supplier: "ACME",
    supplierLogo: { supplierLogo },
    supplierLocation: "RAK",
    supplierReview: {
      verdict: "Very Good",
      count: 583,
    },
    supplierLegacy: {
      value: 3,
      units: "YRS",
    },
  },
];
