import * as S from "./FAQ.styled";

import Container from "@/components/Container/Container";
import Head from "next/head";

export const FAQ: React.FC = () => {
  return (
    <>
      <Head>
        <title>Lumsum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container fluidContainer>
        <S.ContainerInnerWrap>
          <S.HomeSection>
            <S.HomeSectionTitle>Frequently Asked Questions</S.HomeSectionTitle>

            <S.Question>1. What is Lumsum and how can I search in Lumsum?</S.Question>
            <S.Answer>Lumsum is your one-stop solution for the latest construction materials and tools. With lumsum you are always a click away from connecting with suppliers you are looking for. The website is made to be simple and friendly, but still covers all the categories needed. Each category has a sub-category to narrow it down. Once chosen it will provide you with the business that can supply it to you. You can scroll, select and contact the supplier.</S.Answer>

            <S.Question>2. What is the meaning of Lumsum ?</S.Question>
            <S.Answer>Lumsum is the way the market here pronounces Lumpsum. It is meant to show that the website can cater to all your construction needs.</S.Answer>

            <S.Question>3. How do I get my business listed?</S.Question>
            <S.Answer>We like to keep it personal. Drop us you email, number, and city in the contact us form, and our representative will contact you.</S.Answer>
            <S.Answer>Keep in mind that there are NO CHARGES to be a member of our website.</S.Answer>

            <S.Question>4. How do I register a user ?</S.Question>
            <S.List>
              <S.ListItem>On the Lumsum home page, select your login icon in the top right-hand corner.</S.ListItem>
              <S.ListItem>Click Register and select a username of your choice in the name area (publicly visible)</S.ListItem>
              <S.ListItem>Enter your e-mail and add an appropriate password.</S.ListItem>
              <S.ListItem>Click Register to confirm. Now you can choose a new profile picture and add as many reviews as you want.</S.ListItem>
            </S.List>

            <S.Question>5. Can I buy directly from the website?</S.Question>
            <S.Answer>Lumsum offers the direct contact information of suppliers, but we help you decide by showing their ratings and sharing reviews about them by other users.</S.Answer>

            <S.Question>6. Does your site edit the content of the reviews published?</S.Question>
            <S.Answer>Absolutely no! We work hard to create a site that is helpful and maintains high-quality, relevant content. Therefore, every review must be connected to a user profile that has a real person behind it. We will always make sure that the reviews are here to provide valuable insights and feedbacks of the suppliers' products.</S.Answer>

            <S.Question>7. What cities do you cover?</S.Question>
            <S.Answer>We are currently covering all seven emirates of the UAE. Hopefully, we will expand our services to other countries in the Middle East.</S.Answer>

            <S.Question>8. How much does Lumsum cost?</S.Question>
            <S.Answer>Business listing is FREE, and users registration is FREE.</S.Answer>

            <S.Question>9. How does Lumsum help my Business grow?</S.Question>
            <S.Answer>Being a part of Lumsum family will help your business attract more customers. We will showcase your business details with direct contact information to make reaching you easily like never before. We will also notify you and allow you to respond to reviews or ask for more information about customers' experience.</S.Answer>

            <S.Question>10. Do I need a user account to use Lumsum?</S.Question>
            <S.Answer>If you just want to read reviews and check our categories you don't need a user account, but you'll definitely need one if you want to write a review!</S.Answer>

            <S.Question>11. Why my review is removed ?</S.Question>
            <S.Answer>Users'reviews and vendor responses to a review must be respectful and constructive and may not contain abusive, hateful, threatening, or harassing content. Any fraudulent review or response that violate these Guidelines may be removed.</S.Answer>

            <S.Question>12. Can't find what you're looking for ?</S.Question>
            <S.Answer>We are always here for you, contact us directly on</S.Answer>
            <S.Answer>+(971) - 056 5423746</S.Answer>
            <S.Answer>+(971) - 056 5427286</S.Answer>
            <S.Answer>or send us an e-mail to info@lumsum.io</S.Answer>
          </S.HomeSection>
        </S.ContainerInnerWrap>
      </Container>
    </>
  );
};
