import Head from "next/head";
import Layout from "@/layout/Layout";
import { ReactChild } from "react";
import { Formik } from "formik";
import * as Yup from "yup";
import AuthenticationBox from "@/components/AuthenticationBox/AuthenticationBox";
import Form from "@/components/Form/Form";
import FormGroup from "@/components/FormGroup/FormGroup";
import ButtonWrap from "@/components/ButtonWrap/ButtonWrap";
import Button from "@/components/Button/Button";
import Container from "@/components/Container/Container";

interface ForgotPasswordFormValues {
  email: string;
}

const ForgotPasswordSchema = Yup.object().shape({
  email: Yup.string().email("Invalid email").required("Required"),
});

interface IProps { }
export const ForgotPassword: any = () => {
  return (
    <>
      <Head>
        <title>Lumsum Recover Password</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <AuthenticationBox
          altOptionLink="/user/login"
          altOptionLinkText="Back to login"
        >
          <Formik
            initialValues={{
              email: "",
            }}
            validationSchema={ForgotPasswordSchema}
            onSubmit={(values) => {
              console.log("");
            }}
          >
            {({ errors, touched }) => (
              <Form>
                <FormGroup
                  label="Email"
                  id="email"
                  placeholder="abc@domain.com"
                  requiredField
                  errors={errors}
                  touched={touched}
                />
                <ButtonWrap marginTop="0">
                  <Button theme="primary" size="medium" fullWidth type="submit">
                    Submit
                  </Button>
                </ButtonWrap>
              </Form>
            )}
          </Formik>
        </AuthenticationBox>
      </Container>
    </>
  );
};

ForgotPassword.getLayout = function PageLayout(page: ReactChild) {
  return (
    <Layout isMinimal title="Forgot Password">
      {page}
    </Layout>
  )
}
