import Head from "next/head";
import Image from "next/image";
import SidebarSecondary from "@/components/SidebarSecondary/SidebarSecondary";
import RatingDetailed from "@/components/RatingDetailed/RatingDetailed";
import ProductInfoSquare from "@/components/ProductInfoSquare/ProductInfoSquare";
import ContentTable from "@/components/ContentTable/ContentTable";
import Container from "@/components/Container/Container";
import ContainerMainFixedAside from "@/components/ContainerMainFixedAside/ContainerMainFixedAside";
import ContainerMainContent from "@/components/ContainerMainContent/ContainerMainContent";
import Box from "@/components/Box/Box";

import * as S from "./SupplierDetails.styled";

import { Element } from "react-scroll";

import CONTACT from "@/assets/images/contact.svg";
import EMAIL from "@/assets/images/email.svg";
import FACEBOOK from "@/assets/images/facebook.svg";
import INSTAGRAM from "@/assets/images/instagram.svg";
import MAP_MARKER from "@/assets/images/map-marker.svg";
import MOBILE from "@/assets/images/mobile.svg";
import OVERVIEW from "@/assets/images/overview.svg";
import PHONE from "@/assets/images/phone.svg";
import PRODUCTS from "@/assets/images/products.svg";
import REVIEWS from "@/assets/images/reviews.svg";
import WHATSAPP from "@/assets/images/whatsapp.svg";

import { supplier, productsData } from "@/dummy-data/suppliers";

import { Swiper, SwiperSlide } from "swiper/react";
import { Pagination, Navigation } from "swiper";
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";

const menuList = [
  {
    title: "Overview",
    icon: OVERVIEW,
    url: "/suppliers#overview",
    key: "1",
  },
  {
    title: "Products",
    icon: PRODUCTS,
    url: "/suppliers#products",
    key: "2",
  },
  {
    title: "Reviews",
    icon: REVIEWS,
    url: "/suppliers#reviews",
    key: "3",
  },
];

interface IProps { }

export const SupplierDetails: any = () => {
  return (
    <>
      <Head>
        <title>Supplier</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <SidebarSecondary menuList={menuList} selected="1" onLinkClick />
        <ContainerMainFixedAside>
          <ContainerMainContent>
            <Element name="Overview">
              <Box title="Overview" id={"overview"}>
                <S.InnerWrap>
                  <S.SupplierOverViewHead data={supplier} />
                  <S.InfoBlock>
                    <S.SubTitle1>About</S.SubTitle1>
                    <S.Text>{supplier.about}</S.Text>
                  </S.InfoBlock>
                  <S.InfoBlock>
                    <S.SubTitle1>Details</S.SubTitle1>
                    <ContentTable data={supplier.details} />
                  </S.InfoBlock>
                  <S.InfoBlock>
                    <S.SubTitle1>Brands</S.SubTitle1>
                    <S.BrandList tags={supplier.brands} />
                  </S.InfoBlock>
                  <S.InfoBlock>
                    <S.SubTitle1>Categories</S.SubTitle1>
                    <S.BrandList
                      colorTheme="highlight"
                      tags={supplier.categories}
                    />
                  </S.InfoBlock>
                  {supplier.contactInfo && (
                    <S.InfoBlock>
                      <S.SubTitle1>Contact us</S.SubTitle1>
                      <S.ListContactInfo>
                        {supplier.contactInfo.address && (
                          <S.ListLiContactInfo>
                            <a
                              title="Open in maps"
                              href={supplier.contactInfo.address}
                              target="_blank"
                            >
                              <S.IconWrapContactInfo>
                                <Image src={MAP_MARKER} layout="fill" />
                              </S.IconWrapContactInfo>
                              <S.TextContactInfo>
                                {supplier.contactInfo.address}
                              </S.TextContactInfo>
                            </a>
                          </S.ListLiContactInfo>
                        )}
                        {supplier.contactInfo.phone && (
                          <S.ListLiContactInfo>
                            <a
                              title="Call"
                              href={supplier.contactInfo.phone}
                              target="_blank"
                            >
                              <S.IconWrapContactInfo>
                                <Image src={PHONE} layout="fill" />
                              </S.IconWrapContactInfo>
                              <S.TextContactInfo>
                                {supplier.contactInfo.phone}
                              </S.TextContactInfo>
                            </a>
                          </S.ListLiContactInfo>
                        )}
                        {supplier.contactInfo.mobile && (
                          <S.ListLiContactInfo>
                            <a
                              title="Call"
                              href={supplier.contactInfo.mobile}
                              target="_blank"
                            >
                              <S.IconWrapContactInfo>
                                <Image src={MOBILE} layout="fill" />
                              </S.IconWrapContactInfo>
                              <S.TextContactInfo>
                                {supplier.contactInfo.mobile}
                              </S.TextContactInfo>
                            </a>
                          </S.ListLiContactInfo>
                        )}
                        {supplier.contactInfo.email && (
                          <S.ListLiContactInfo>
                            <a
                              title="Send email"
                              href={supplier.contactInfo.email}
                              target="_blank"
                            >
                              <S.IconWrapContactInfo>
                                <Image src={EMAIL} layout="fill" />
                              </S.IconWrapContactInfo>
                              <S.TextContactInfo>
                                {supplier.contactInfo.email}
                              </S.TextContactInfo>
                            </a>
                          </S.ListLiContactInfo>
                        )}
                        {(supplier.contactInfo.facebook ||
                          supplier.contactInfo.instagram ||
                          supplier.contactInfo.whatsapp) && (
                            <S.ListLinearContactInfo>
                              {supplier.contactInfo.facebook && (
                                <S.ListLinearLiContactInfo>
                                  <a
                                    title="Visit us in facebook"
                                    href={supplier.contactInfo.facebook}
                                    target="_blank"
                                  >
                                    <S.ListLinearIconWrapContactInfo>
                                      <Image src={FACEBOOK} layout="fill" />
                                    </S.ListLinearIconWrapContactInfo>
                                  </a>
                                </S.ListLinearLiContactInfo>
                              )}
                              {supplier.contactInfo.instagram && (
                                <S.ListLinearLiContactInfo>
                                  <a
                                    title="Visit our Instagram page"
                                    href={supplier.contactInfo.instagram}
                                    target="_blank"
                                  >
                                    <S.ListLinearIconWrapContactInfo>
                                      <Image src={INSTAGRAM} layout="fill" />
                                    </S.ListLinearIconWrapContactInfo>
                                  </a>
                                </S.ListLinearLiContactInfo>
                              )}
                              {supplier.contactInfo.whatsapp && (
                                <S.ListLinearLiContactInfo>
                                  <a
                                    title="Send us a message in Whatsapp"
                                    href={supplier.contactInfo.whatsapp}
                                    target="_blank"
                                  >
                                    <S.ListLinearIconWrapContactInfo>
                                      <Image src={WHATSAPP} layout="fill" />
                                    </S.ListLinearIconWrapContactInfo>
                                  </a>
                                </S.ListLinearLiContactInfo>
                              )}
                            </S.ListLinearContactInfo>
                          )}
                      </S.ListContactInfo>
                    </S.InfoBlock>
                  )}
                </S.InnerWrap>
              </Box>
            </Element>
            <Element name="Products">
              <Box title="Products" id={"products"}>
                <S.Slider>
                  <Swiper
                    modules={[Pagination, Navigation]}
                    spaceBetween={16}
                    slidesPerView={"auto"}
                    pagination={{ clickable: true }}
                  >
                    {productsData.map((product, index) => {
                      return (
                        <SwiperSlide key={index}>
                          <ProductInfoSquare
                            key={product.name}
                            data={product}
                          />
                        </SwiperSlide>
                      );
                    })}
                  </Swiper>
                </S.Slider>
              </Box>
            </Element>
            <Element name="Reviews">
              <Box title="Reviews" id={"reviews"}>
                <S.SummaryRatingOverview
                  size="large"
                  rating={supplier.review}
                />
                <RatingDetailed ratingDetail={supplier.ratingDetail} />
              </Box>
            </Element>
          </ContainerMainContent>
        </ContainerMainFixedAside>
      </Container>
    </>
  );
};
