import * as S from "./Home.styled";

import { blogData, categories, clients } from "@/dummy-data/home";
import { howItWorks, whyLumsum } from "@/cms-data/home";

import BANNER_1 from "@/assets/images/homepage/banner1.svg";
// import BANNER_1_CROPPED from "@/assets/images/homepage/banner1-cropped.jpg";
import BANNER_2 from "@/assets/images/homepage/banner2.svg";
import BANNER_3 from "@/assets/images/homepage/banner3.svg";
import BlogList from "@/components/BlogList/BlogList";
import CategoriesList from "@/components/CategoriesList/CategoriesList";
import Container from "@/components/Container/Container";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

interface IProps {}

export const Home: any = () => {
  return (
    <>
      <Head>
        <title>Lumsum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container fluidContainer>
        <S.CarouselWrapper autoplay>
          <S.Banner background={BANNER_1}>
            <S.BannerTitle>
              We Supply <S.BannerTitleSub>Precision</S.BannerTitleSub>
            </S.BannerTitle>
            <S.BannerText>
              Complete your projects on time, and spend less on procurement.
              Find suppliers faster, and cheaper with us.
            </S.BannerText>
            <S.BannerLinkWrap>
              <Link href="/products">
                <S.BannerLinks primary>
                  Find
                  <br />
                  Supplies
                </S.BannerLinks>
              </Link>
              <Link href="/">
                <S.BannerLinks>
                  Talk to
                  <br />
                  an Expert
                </S.BannerLinks>
              </Link>
            </S.BannerLinkWrap>
          </S.Banner>
          <S.Banner background={BANNER_2}>
            <S.BannerTitle>
              We Supply <S.BannerTitleSub>Transparency</S.BannerTitleSub>
            </S.BannerTitle>
            <S.BannerText>
              A massive collection of authentic and verified data for you to
              choose from. Search and order products from our trusted suppliers.
            </S.BannerText>
            <S.BannerLinkWrap>
              <Link href="/products">
                <S.BannerLinks primary>
                  Find
                  <br />
                  Supplies
                </S.BannerLinks>
              </Link>
              <Link href="/">
                <S.BannerLinks>
                  Talk to
                  <br />
                  an Expert
                </S.BannerLinks>
              </Link>
            </S.BannerLinkWrap>
          </S.Banner>
          <S.Banner background={BANNER_3}>
            <S.BannerTitle>
              We Supply{" "}
              <S.BannerTitleSub>Ease&nbsp;of&nbsp;Mind</S.BannerTitleSub>
            </S.BannerTitle>
            <S.BannerText>
              Spend more time growing your business, and serving customers.
              Order supplies and let us handle the logistics and delivery.
            </S.BannerText>
            <S.BannerLinkWrap>
              <Link href="/products">
                <S.BannerLinks primary>
                  Find
                  <br />
                  Supplies
                </S.BannerLinks>
              </Link>
              <Link href="/">
                <S.BannerLinks>
                  Talk to
                  <br />
                  an Expert
                </S.BannerLinks>
              </Link>
            </S.BannerLinkWrap>
          </S.Banner>
        </S.CarouselWrapper>
        <S.ContainerInnerWrap>
          <S.HomeSection>
            <S.HomeSectionTitle>Why LUMSUM</S.HomeSectionTitle>
            <S.WhyCardsGrid>
              {whyLumsum.map((content) => {
                return (
                  <S.WhyCards key={content.title}>
                    <S.WhyCardsImageWrap>
                      <Image src={content.icon} layout="fill" />
                    </S.WhyCardsImageWrap>
                    <S.WhyCardsTitle>{content.title}</S.WhyCardsTitle>
                    <S.WhyCardsText>{content.text}</S.WhyCardsText>
                  </S.WhyCards>
                );
              })}
            </S.WhyCardsGrid>
            <S.HomeSectionBtnContainer>
              <S.BannerLinks primary>
                Start saving time and money... Order now
              </S.BannerLinks>
            </S.HomeSectionBtnContainer>
          </S.HomeSection>

          <S.HomeSection>
            <S.HomeSectionTitle>How it works</S.HomeSectionTitle>
            <S.HowItWorksCardsGrid>
              {howItWorks.map((content) => {
                return (
                  <S.HowItWorksCards key={content.title}>
                    <S.HowItWorksCardsImageWrap>
                      <Image src={content.icon} layout="fill" />
                    </S.HowItWorksCardsImageWrap>
                    <S.HowItWorksCardsTextWrap>
                      <S.HowItWorksCardsTitle>
                        {content.title}
                      </S.HowItWorksCardsTitle>
                      <S.HowItWorksCardsText>
                        {content.text}
                      </S.HowItWorksCardsText>
                    </S.HowItWorksCardsTextWrap>
                  </S.HowItWorksCards>
                );
              })}
            </S.HowItWorksCardsGrid>
          </S.HomeSection>

          <S.HomeSection>
            <S.HomeSectionTitle>Who we work with</S.HomeSectionTitle>
            <S.ClientsGrid>
              {clients.map((client) => {
                return (
                  <S.ClientCards title={client.alt} key={client.alt}>
                    <S.ClientImageWrap>
                      <S.GreyImg
                        src={client.icon}
                        layout="fill"
                        alt={client.alt}
                      />
                    </S.ClientImageWrap>
                  </S.ClientCards>
                );
              })}
            </S.ClientsGrid>
          </S.HomeSection>

          <S.HomeSection>
            <S.HomeSectionTitle>Categories</S.HomeSectionTitle>
            <CategoriesList data={categories} />
          </S.HomeSection>

          <S.HomeSection>
            <S.HomeSectionTitle>
              <Link href="/blogs">
                <a>News &amp; Blogs</a>
              </Link>
            </S.HomeSectionTitle>
            <BlogList data={blogData} />
          </S.HomeSection>
        </S.ContainerInnerWrap>
      </Container>
    </>
  );
};
