import * as S from "./Products.styled";

import Head from "next/head";
import MobilePreferenceBlock from "@/components/MobilePreferenceBlock/MobilePreferenceBlock";
import Container from "@/components/Container/Container";
import ContainerMainTitle from "@/components/ContainerMainTitle/ContainerMainTitle";
import ProductCard from "@/components/ProductCard/ProductCard";
import Button from "@/components/Button/Button";
import { products } from "@/dummy-data/products/products";
import useFilterStore from "@/store/useFilterStore";
import { useState } from "react";


export const Products: any = () => {
  const [currentLoad, setCurrentLoad] = useState(6);
  const perPage = 6;
  let currentPage = 1;
  return (
    <>
      <Head>
        <title>Lumsum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <S.HomeFilters
          visible={useFilterStore((state) => state.isFilterVisible)}
          productsOrSuppliers="products"
        />
        <S.ProductsContainer>
          <MobilePreferenceBlock productsOrSuppliers="products" />
          <ContainerMainTitle descriptionLike>
            {products.length} results for&nbsp;<S.BoldThemeText>drill</S.BoldThemeText>
            &nbsp;products
          </ContainerMainTitle>
          <S.CardGrid>
            {products.slice(0, currentLoad).map((product, index) => {
              return <ProductCard key={index} data={product} />;
            })}
          </S.CardGrid>
          {products.length > currentLoad && (
            <S.LoadMoreWrap>
              <Button
                theme="primary"
                onClick={() => {
                  setCurrentLoad(perPage * ++currentPage)
                }}
              >Load more</Button>
            </S.LoadMoreWrap>
          )}
        </S.ProductsContainer>
      </Container>
    </>
  );
};
