import * as S from "./Suppliers.styled";

import Head from "next/head";
import MobilePreferenceBlock from "@/components/MobilePreferenceBlock/MobilePreferenceBlock";
import SupplierCard from "@/components/SupplierCard/SupplierCard";
import Container from "@/components/Container/Container";
import ContainerMainTitle from "@/components/ContainerMainTitle/ContainerMainTitle";
import Button from "@/components/Button/Button";
import { suppliers } from "@/dummy-data/suppliers";
import useFilterStore from "@/store/useFilterStore";
import { useState } from "react";


export const Suppliers: any = () => {
  const [currentLoad, setCurrentLoad] = useState(6);
  const perPage = 6;
  let currentPage = 1;
  return (
    <>
      <Head>
        <title>Suppliers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <S.HomeFilters
          visible={useFilterStore((state) => state.isFilterVisible)}
          productsOrSuppliers="suppliers"
        />
        <S.SuppliersContainer>
          <MobilePreferenceBlock productsOrSuppliers="suppliers" />
          <ContainerMainTitle descriptionLike>
            {suppliers.length} results for&nbsp;<S.BoldThemeText>drill</S.BoldThemeText>
            &nbsp;suppliers
          </ContainerMainTitle>
          <S.cardGrid>
            {suppliers.slice(0, currentLoad).map((supplier, index) => {
              return <SupplierCard key={index} data={supplier} />;
            })}
          </S.cardGrid>
          {suppliers.length > currentLoad && (
            <S.LoadMoreWrap>
              <Button
                theme="primary"
                onClick={() => {
                  setCurrentLoad(perPage * ++currentPage)
                }}
              >Load more</Button>
            </S.LoadMoreWrap>
          )}
        </S.SuppliersContainer>
      </Container>
    </>
  );
};
