import Head from "next/head";
import BlogCard from "@/components/BlogCard/BlogCard";
import Container from "@/components/Container/Container";
import ContainerMain from "@/components/ContainerMain/ContainerMain";
import ContainerMainContent from "@/components/ContainerMainContent/ContainerMainContent";
import ContainerMainTitle from "@/components/ContainerMainTitle/ContainerMainTitle";
import { blogData } from "@/dummy-data/blog";

import * as S from "./Blogs.styled";

interface BlogProps {
  title: string;
  icon: string;
  iconAlt: string;
  url: string;
};

export const Blogs: any = () => {
  return (
    <>
      <Head>
        <title>Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <ContainerMain>
          <ContainerMainTitle>Blogs</ContainerMainTitle>
          <ContainerMainContent>
            <S.BlogList>
              {blogData.map((blog: BlogProps) => {
                return (
                  <S.BlogListLi key={blog.title}>
                    <BlogCard
                      title={blog.title}
                      icon={blog.icon}
                      iconAlt={blog.iconAlt}
                      url={blog.url}
                    />
                  </S.BlogListLi>
                );
              })}
            </S.BlogList>
          </ContainerMainContent>
        </ContainerMain>
      </Container>
    </>
  );
};
