import { useState, useEffect } from "react";
import { useRouter } from 'next/router';
import Head from "next/head";
import SidebarSecondary from "@/components/SidebarSecondary/SidebarSecondary";
import InfoCardPlain from "@/components/InfoCardPlain/InfoCardPlain";
import ProfileSettingsModal from "@/components/ProfileSettingsModal/ProfileSettingsModal";
import Container from "@/components/Container/Container";
import ContainerMainContent from "@/components/ContainerMainContent/ContainerMainContent";
import ContainerMainFixedAside from "@/components/ContainerMainFixedAside/ContainerMainFixedAside";
import { useSession } from "next-auth/react"
import AuthMessage from "@/components/AuthMessage/AuthMessage";

import iconAddresses from "@/assets/images/addresses.svg";
import iconOrders from "@/assets/images/orders.svg";
import iconPayments from "@/assets/images/payments.svg";
import iconProfile from "@/assets/images/profile.svg";
import useAuthStore from "@/store/useAuthStore";

const menuList = [
  {
    title: "Profile",
    icon: iconProfile,
    url: "/account/profile",
    key: "1",
  },
  {
    title: "Orders",
    icon: iconOrders,
    url: "/account/orders",
    key: "2",
  },
  {
    title: "Addresses",
    icon: iconAddresses,
    url: "/account/addresses",
    key: "3",
  },
  {
    title: "Payments",
    icon: iconPayments,
    url: "/account/payments",
    key: "4",
  },
];

export const Profile: any = () => {

  const [IsProfileSettingsModalVisible, setIsProfileSettingsModalVisible] =
    useState(false);

  const showProfileSettingsModal = () => {
    setIsProfileSettingsModalVisible(true);
  };

  const handleOkProfileSettingsModal = () => {
    setIsProfileSettingsModalVisible(false);
  };

  const handleCancelProfileSettingsModal = () => {
    setIsProfileSettingsModalVisible(false);
  };

  const userData = {
    info: [
      {
        title: "Name",
        text: "Mahmoud Elsoukie",
      },
      {
        title: "Address",
        text: "Umm Suqeim St - Dubai",
      },
      {
        title: "Organization",
        text: "RAK",
      },
      {
        title: "Phone",
        text: "+971-50-471-4556",
      },
      {
        title: "Email",
        text: "mahmoudelsoukie@rak.com",
      },
    ],
    buttons: [
      {
        text: "Edit Profile",
        theme: "primary",
        onClickHandler: () => {
          showProfileSettingsModal();
        },
      },
    ],
  };


  let { data: session, status } = useSession();
  const sessionStore = useAuthStore((state) => state.session);
  status = sessionStore ? "authenticated" : "unauthenticated";

  const router = useRouter()

  useEffect(() => {
    if (!sessionStore) {
      router.push('/');
    }
  }, []);

  // if (status === "loading") {
  //   <AuthMessage>
  //     <p>Loading</p>
  //   </AuthMessage>
  // }
  if (status === "unauthenticated") {
    return (
      <AuthMessage>
        {/* <p>Access Denied</p> */}
      </AuthMessage>
    )
  }

  return (
    <>
      <Head>
        <title>Overview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <SidebarSecondary
          menuList={menuList}
          selected="1"
          header={{ userName: "Mahmoud" }}
        />
        <ContainerMainFixedAside>
          <ContainerMainContent>
            <InfoCardPlain data={userData} />
          </ContainerMainContent>
        </ContainerMainFixedAside>
      </Container>
      <ProfileSettingsModal
        visible={IsProfileSettingsModalVisible}
        handleOkProfileSettingsModal={handleOkProfileSettingsModal}
        handleCancelProfileSettingsModal={handleCancelProfileSettingsModal}
      />
    </>
  );
};
