import * as S from "./About.styled";

import Container from "@/components/Container/Container";
import Head from "next/head";
import Image from "next/image";
import { whatIsLumsum } from "@/cms-data/about";

interface IProps { }

export const About: any = () => {
  return (
    <>
      <Head>
        <title>Lumsum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container fluidContainer>
        <S.ContainerInnerWrap>
          <S.HomeSection>
            <S.HomeSectionTitle>What is Lumsum?</S.HomeSectionTitle>
            <S.WhyCardsGrid>
              {whatIsLumsum.map((content) => {
                return (
                  <S.WhyCards key={content.title}>
                    <S.WhyCardsImageWrap>
                      <Image src={content.icon} layout="fill" />
                    </S.WhyCardsImageWrap>
                    <S.WhyCardsTitle>{content.title}</S.WhyCardsTitle>
                    <S.WhyCardsText>{content.text}</S.WhyCardsText>
                  </S.WhyCards>
                );
              })}
            </S.WhyCardsGrid>
          </S.HomeSection>
        </S.ContainerInnerWrap>
      </Container>
    </>
  );
};
